#+title: Glossing Conventions for Classical Japanese in JSON Format
#+author: idiig

This repository provides a JSON format for glossing Classical Japanese
texts, following established linguistic conventions mainly focused on
the translation of Classical Japanese texts into English, Chinese
(e.g., the [[https://github.com/idiig/tosa-nikki-chinese-translation/tree/master][Tosa Nikki/Tosa Diary]] Chinese translation).

Based on the following references:

- [[https://www.eva.mpg.de/lingua/resources/glossing-rules.php][Max Planck Institute for Evolutionary Anthropology, Department of
  Linguistics (2015). Leipzig Glossing Rules: Conventions for
  interlinear morpheme-by-morpheme glosses.]]
- [[https://researchmap.jp/mzisk/published_papers/42178558][Zisk, Matthew (2023). “Glossing Glosses: Methods for Transcribing
  and Glossing Japanese Kundoku Texts.” In Franck Cinato et
  al. (eds.), Glossing Practice: Comparative Perspectives,
  pp. 47–82. Lexington Books.]]
- [[https://researchmap.jp/mzisk/misc/47645778][ジスク マシュー (Zisk, Matthew) (2024). 古代日本語と現代日本語の機能
  形態素リスト (2024.09.10).]]
- [[https://michinorishimoji.github.io/searchgloss/][下地 理則 (Shimoji, Michinori) (2025). SearchGloss (Version
  1.0). DOI: 10.5281/zenodo.16419404.]]

This is originally for personal use. Use at your own risk.

* Usage workflow (for idiig/tosa-translation project)
- Generate general glossary for specific documents with Zisk's list
- Manually deal unavailable glossary entries => glossary.json
- Use glossary.json to fill in missing =glossary_abbreviations= in the main document
